/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package evaluator;

import jess.Userfunction;
import seakers.orekit.util.OrekitConfig;
import vassar.GlobalScope;
import vassar.VassarClient;
import vassar.database.DatabaseClient;
import vassar.database.service.DebugAPI;
import vassar.database.service.QueryAPI;
import vassar.jess.Resource;
import vassar.jess.Requests;
import vassar.jess.func.Improve;
import vassar.jess.func.SameOrBetter;
import vassar.jess.func.Worsen;
import sqs.Consumer;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.auth.credentials.EnvironmentVariableCredentialsProvider;


import java.net.URI;
import java.util.ArrayList;
import java.util.HashMap;

public class EvaluatorApp {

    public static void main(String[] args) {
        // System.setProperty("orekit.coveragedatabase", "/Users/gabeapaza/repositories/seakers/design_evaluator/app/src/main/java/vassar/evaluator/coverage/orekit/CoverageDatabase");
        System.setProperty("orekit.coveragedatabase", System.getenv("COVERAGE_DATABASE")); // DOCKER



//       __  .__   __.  __  .___________.
//      |  | |  \ |  | |  | |           |
//      |  | |   \|  | |  | `---|  |----`
//      |  | |  . `  | |  |     |  |
//      |  | |  |\   | |  |     |  |
//      |__| |__| \__| |__|     |__|


        // OrekitConfig.init(1, "/Users/gabeapaza/repositories/seakers/design_evaluator/app/src/main/java/vassar/evaluator/coverage/orekit");
        OrekitConfig.init(1, System.getenv("OREKIT_INIT")); // DOCKER

        GlobalScope.measurementsToSubobjectives = new HashMap<>();
        GlobalScope.subobjectivesToMeasurements = new HashMap<>();

        // String rootPath = "/Users/gabeapaza/repositories/seakers/design_evaluator";
        String rootPath = ""; // DOCKER


        String outputFilePath     = rootPath + "/app/debug/dbOutput.json";
        String outputPath         = rootPath + "/app/debug";
        String apollo_url         = "http://172.18.0.8:8080/v1/graphql";
        String localstackEndpoint = "http://172.18.0.3:4576";
        String queue_url          = "http://172.18.0.3:4576/queue/test_queue";
        boolean debug             = true;

        int group_id   = 1;
        int problem_id = 5;

        ArrayList<Userfunction> userFuncs = new ArrayList<>() {{
            add( new SameOrBetter() );
            add( new Improve() );
            add( new Worsen() );
        }};


        // -----> JESS REQUESTS <-----
        String jessGlobalTempPath = rootPath + "/app/src/main/java/vassar/database/template/defs";
        String jessGlobalFuncPath = rootPath + "/app/src/main/java/vassar/jess/utils/clp";
        String jessAppPath        = rootPath + "/app/problems/smap/clp";
        String requestMode        = "CRISP-ATTRIBUTES";
        Requests requests = new Requests.Builder()
                                        .setGlobalTemplatePath(jessGlobalTempPath)
                                        .setGlobalFunctionPath(jessGlobalFuncPath)
                                        .setFunctionTemplates()
                                        .setRequestMode(requestMode)
                                        .setJessAppPath(jessAppPath)
                                        .build();





//      .______    __    __   __   __       _______
//      |   _  \  |  |  |  | |  | |  |     |       \
//      |  |_)  | |  |  |  | |  | |  |     |  .--.  |
//      |   _  <  |  |  |  | |  | |  |     |  |  |  |
//      |  |_)  | |  `--'  | |  | |  `----.|  '--'  |
//      |______/   \______/  |__| |_______||_______/


        QueryAPI queryAPI = new QueryAPI.Builder(apollo_url)
                                        .groupID(group_id)
                                        .problemID(problem_id)
                                        .build();

        DebugAPI debugAPI = new DebugAPI.Builder(outputFilePath)
                                        .newFile()
                                        .setOutputPath(outputPath)
                                        .build();

        DatabaseClient dbClient = new DatabaseClient.Builder()
                                        .debug(debug)
                                        .queryClient(queryAPI)
                                        .debugClient(debugAPI)
                                        .build();



        Resource engine = new Resource.Builder(dbClient)
                                        .addUserFunctionBatch(userFuncs)      // - Improve(), SameOrBetter(), Worsen()
                                        .setRequests(requests.getRequests()) // - eval: template requests (+ functions)
                                        .setRequestMode(requestMode)
                                        .build();



        VassarClient vClient = new VassarClient.Builder()
                                        .setEngine(engine)
                                        .build();







        SqsClient sqsClient = SqsClient.builder()
                                        .region(Region.US_EAST_2)
                                        .endpointOverride(URI.create(localstackEndpoint))
                                        .credentialsProvider(EnvironmentVariableCredentialsProvider.create())
                                        .build();




        Consumer evaluator = new Consumer.Builder(sqsClient)
                                         .setVassarClient(vClient)
                                         .setQueueUrl(queue_url)
                                         .debug(debug)
                                         .build();

        // RUN CONSUMER
        Thread cThread = new Thread(evaluator);
        cThread.start();





    }
}
