(defglobal ?*app_path* = "{{appPath}}")
(import vassar.*)
(import vassar.jess.utils.*)
(import vassar.result.*)
(import java.util.*)
(import jess.*)
(defglobal ?*rulesMap* = (new java.util.HashMap))
(set-reset-globals nil)