(deffunction worth-improving-measurement (?meas)
    (bind ?worth TRUE)
    (bind ?arr (matlabf get_related_suboj ?meas))
    (if (eq ?arr nil) then (return FALSE))
    (bind ?iter (?arr iterator))
    (while (?iter hasNext)
    (bind ?subobj (?iter next))
    (if (eq (eval ?subobj) 1) then (bind ?worth FALSE)))
    (return ?worth))